seed_everything: 42

trainer:
  logger: 
    class_path: pytorch_lightning.loggers.WandbLogger
    init_args:
      name: DiffMST_naive_advanced_combined_data
      project: DiffMST
      save_dir: /data/scratch/acw639/DiffMST/logs
  enable_checkpointing: true
  callbacks:
    - class_path: mst.callbacks.audio.LogAudioCallback
    - class_path: pytorch_lightning.callbacks.ModelSummary
      init_args: 
        max_depth: 2
  default_root_dir: null
  gradient_clip_val: 4.0
  devices: 1
  check_val_every_n_epoch: 1
  max_steps: 1000000
  log_every_n_steps: 50
  accelerator: gpu
  sync_batchnorm: true
  precision: 32
  enable_model_summary: true
  num_sanity_val_steps: 2
  benchmark: true
  accumulate_grad_batches: 4
  reload_dataloaders_every_n_epochs: 1
